//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.3053 版自动生成。
// 
#pragma warning disable 1591

namespace ShareMan.SB {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ShareBrowseSoap", Namespace="http://tempuri.org/")]
    public partial class ShareBrowse : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PublishMovieOperationCompleted;
        
        private System.Threading.SendOrPostCallback PublishCartoonOperationCompleted;
        
        private System.Threading.SendOrPostCallback PublishSoftOperationCompleted;
        
        private System.Threading.SendOrPostCallback PublishMusicOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ShareBrowse() {
            this.Url = global::ShareMan.Properties.Settings.Default.ShareMan_SB_ShareBrowse;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PublishMovieCompletedEventHandler PublishMovieCompleted;
        
        /// <remarks/>
        public event PublishCartoonCompletedEventHandler PublishCartoonCompleted;
        
        /// <remarks/>
        public event PublishSoftCompletedEventHandler PublishSoftCompleted;
        
        /// <remarks/>
        public event PublishMusicCompletedEventHandler PublishMusicCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PublishMovie", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PublishMovie(BaseItem baseInfo, Movie mvInfo, long fsId) {
            this.Invoke("PublishMovie", new object[] {
                        baseInfo,
                        mvInfo,
                        fsId});
        }
        
        /// <remarks/>
        public void PublishMovieAsync(BaseItem baseInfo, Movie mvInfo, long fsId) {
            this.PublishMovieAsync(baseInfo, mvInfo, fsId, null);
        }
        
        /// <remarks/>
        public void PublishMovieAsync(BaseItem baseInfo, Movie mvInfo, long fsId, object userState) {
            if ((this.PublishMovieOperationCompleted == null)) {
                this.PublishMovieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPublishMovieOperationCompleted);
            }
            this.InvokeAsync("PublishMovie", new object[] {
                        baseInfo,
                        mvInfo,
                        fsId}, this.PublishMovieOperationCompleted, userState);
        }
        
        private void OnPublishMovieOperationCompleted(object arg) {
            if ((this.PublishMovieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PublishMovieCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PublishCartoon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PublishCartoon(BaseItem baseInfo, Cartoon c) {
            this.Invoke("PublishCartoon", new object[] {
                        baseInfo,
                        c});
        }
        
        /// <remarks/>
        public void PublishCartoonAsync(BaseItem baseInfo, Cartoon c) {
            this.PublishCartoonAsync(baseInfo, c, null);
        }
        
        /// <remarks/>
        public void PublishCartoonAsync(BaseItem baseInfo, Cartoon c, object userState) {
            if ((this.PublishCartoonOperationCompleted == null)) {
                this.PublishCartoonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPublishCartoonOperationCompleted);
            }
            this.InvokeAsync("PublishCartoon", new object[] {
                        baseInfo,
                        c}, this.PublishCartoonOperationCompleted, userState);
        }
        
        private void OnPublishCartoonOperationCompleted(object arg) {
            if ((this.PublishCartoonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PublishCartoonCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PublishSoft", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PublishSoft(BaseItem baseInfo, Software s) {
            this.Invoke("PublishSoft", new object[] {
                        baseInfo,
                        s});
        }
        
        /// <remarks/>
        public void PublishSoftAsync(BaseItem baseInfo, Software s) {
            this.PublishSoftAsync(baseInfo, s, null);
        }
        
        /// <remarks/>
        public void PublishSoftAsync(BaseItem baseInfo, Software s, object userState) {
            if ((this.PublishSoftOperationCompleted == null)) {
                this.PublishSoftOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPublishSoftOperationCompleted);
            }
            this.InvokeAsync("PublishSoft", new object[] {
                        baseInfo,
                        s}, this.PublishSoftOperationCompleted, userState);
        }
        
        private void OnPublishSoftOperationCompleted(object arg) {
            if ((this.PublishSoftCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PublishSoftCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PublishMusic", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PublishMusic(BaseItem baseInfo, Music m) {
            this.Invoke("PublishMusic", new object[] {
                        baseInfo,
                        m});
        }
        
        /// <remarks/>
        public void PublishMusicAsync(BaseItem baseInfo, Music m) {
            this.PublishMusicAsync(baseInfo, m, null);
        }
        
        /// <remarks/>
        public void PublishMusicAsync(BaseItem baseInfo, Music m, object userState) {
            if ((this.PublishMusicOperationCompleted == null)) {
                this.PublishMusicOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPublishMusicOperationCompleted);
            }
            this.InvokeAsync("PublishMusic", new object[] {
                        baseInfo,
                        m}, this.PublishMusicOperationCompleted, userState);
        }
        
        private void OnPublishMusicOperationCompleted(object arg) {
            if ((this.PublishMusicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PublishMusicCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseItem {
        
        private long idField;
        
        private long ownerField;
        
        private System.DateTime birthField;
        
        private string titleField;
        
        private long categoryField;
        
        private long publishTypeField;
        
        private System.DateTime issueDateField;
        
        private string briefField;
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public long Owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Birth {
            get {
                return this.birthField;
            }
            set {
                this.birthField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public long Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public long PublishType {
            get {
                return this.publishTypeField;
            }
            set {
                this.publishTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        /// <remarks/>
        public string Brief {
            get {
                return this.briefField;
            }
            set {
                this.briefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Music {
        
        private string singerField;
        
        private string authorField;
        
        /// <remarks/>
        public string Singer {
            get {
                return this.singerField;
            }
            set {
                this.singerField = value;
            }
        }
        
        /// <remarks/>
        public string Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Software {
        
        private string manufacturerField;
        
        private string versionField;
        
        /// <remarks/>
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cartoon {
        
        private string authorField;
        
        /// <remarks/>
        public string Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Movie {
        
        private string playerField;
        
        private string directorField;
        
        /// <remarks/>
        public string Player {
            get {
                return this.playerField;
            }
            set {
                this.playerField = value;
            }
        }
        
        /// <remarks/>
        public string Director {
            get {
                return this.directorField;
            }
            set {
                this.directorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void PublishMovieCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void PublishCartoonCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void PublishSoftCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void PublishMusicCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591