/* FSMFileSetManSoap12Proxy.h
   Generated by gSOAP 2.7.14 from FileSetMan.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef FSMFileSetManSoap12Proxy_H
#define FSMFileSetManSoap12Proxy_H
#include "FSMH.h"

namespace FSM {

class SOAP_CMAC FileSetManSoap12Proxy : public soap
{ public:
	/// Endpoint URL of service 'FileSetManSoap12Proxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	FileSetManSoap12Proxy();
	/// Constructor with copy of another engine state
	FileSetManSoap12Proxy(const struct soap&);
	/// Constructor with engine input+output mode control
	FileSetManSoap12Proxy(soap_mode iomode);
	/// Constructor with engine input and output mode control
	FileSetManSoap12Proxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~FileSetManSoap12Proxy();
	/// Initializer used by constructor
	virtual	void FileSetManSoap12Proxy_init(soap_mode imode, soap_mode omode);
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'CreateFileSet' (returns error code or SOAP_OK)
	virtual	int CreateFileSet(_ns1__CreateFileSet *ns1__CreateFileSet, _ns1__CreateFileSetResponse *ns1__CreateFileSetResponse);

	/// Web service operation 'QureyFileSet' (returns error code or SOAP_OK)
	virtual	int QureyFileSet(_ns1__QureyFileSet *ns1__QureyFileSet, _ns1__QureyFileSetResponse *ns1__QureyFileSetResponse);

	/// Web service operation 'DeleteFileSet' (returns error code or SOAP_OK)
	virtual	int DeleteFileSet(_ns1__DeleteFileSet *ns1__DeleteFileSet, _ns1__DeleteFileSetResponse *ns1__DeleteFileSetResponse);

	/// Web service operation 'CommitFileSet' (returns error code or SOAP_OK)
	virtual	int CommitFileSet(_ns1__CommitFileSet *ns1__CommitFileSet, _ns1__CommitFileSetResponse *ns1__CommitFileSetResponse);

	/// Web service operation 'ProgressNotify' (returns error code or SOAP_OK)
	virtual	int ProgressNotify(_ns1__ProgressNotify *ns1__ProgressNotify, _ns1__ProgressNotifyResponse *ns1__ProgressNotifyResponse);

	/// Web service operation 'CommitFile' (returns error code or SOAP_OK)
	virtual	int CommitFile(_ns1__CommitFile *ns1__CommitFile, _ns1__CommitFileResponse *ns1__CommitFileResponse);

	/// Web service operation 'CommitError' (returns error code or SOAP_OK)
	virtual	int CommitError(_ns1__CommitError *ns1__CommitError, _ns1__CommitErrorResponse *ns1__CommitErrorResponse);
};

} // namespace FSM

#endif
