/* FSMH.h
   Generated by gSOAP 2.7.14 from FileSetMan.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef FSMH_H
#define FSMH_H
#include "FSMStub.h"

namespace FSM {
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM_byte
#define SOAP_TYPE_FSM_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_FSM_int
#define SOAP_TYPE_FSM_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_FSM_LONG64
#define SOAP_TYPE_FSM_LONG64 (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_LONG64(struct soap*, LONG64 *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_LONG64(struct soap*, const LONG64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_LONG64(struct soap*, const char*, int, const LONG64 *, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_get_LONG64(struct soap*, LONG64 *, const char*, const char*);
SOAP_FMAC3 LONG64 * SOAP_FMAC4 soap_in_LONG64(struct soap*, const char*, LONG64 *, const char*);

#ifndef SOAP_TYPE_FSM_bool
#define SOAP_TYPE_FSM_bool (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_FSM_std__string
#define SOAP_TYPE_FSM_std__string (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

#define soap_new_std__string(soap, n) soap_instantiate_std__string(soap, n, NULL, NULL, NULL)


#define soap_delete_std__string(soap, p) soap_delete(soap, p)

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM__ns1__CommitErrorResponse
#define SOAP_TYPE_FSM__ns1__CommitErrorResponse (24)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__CommitErrorResponse(struct soap*, const char*, int, const _ns1__CommitErrorResponse *, const char*);
SOAP_FMAC3 _ns1__CommitErrorResponse * SOAP_FMAC4 soap_get__ns1__CommitErrorResponse(struct soap*, _ns1__CommitErrorResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__CommitErrorResponse * SOAP_FMAC4 soap_in__ns1__CommitErrorResponse(struct soap*, const char*, _ns1__CommitErrorResponse *, const char*);

#define soap_new__ns1__CommitErrorResponse(soap, n) soap_instantiate__ns1__CommitErrorResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__CommitErrorResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__CommitErrorResponse * SOAP_FMAC4 soap_instantiate__ns1__CommitErrorResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__CommitErrorResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM__ns1__CommitError
#define SOAP_TYPE_FSM__ns1__CommitError (23)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__CommitError(struct soap*, const char*, int, const _ns1__CommitError *, const char*);
SOAP_FMAC3 _ns1__CommitError * SOAP_FMAC4 soap_get__ns1__CommitError(struct soap*, _ns1__CommitError *, const char*, const char*);
SOAP_FMAC3 _ns1__CommitError * SOAP_FMAC4 soap_in__ns1__CommitError(struct soap*, const char*, _ns1__CommitError *, const char*);

#define soap_new__ns1__CommitError(soap, n) soap_instantiate__ns1__CommitError(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__CommitError(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__CommitError * SOAP_FMAC4 soap_instantiate__ns1__CommitError(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__CommitError(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM__ns1__CommitFileResponse
#define SOAP_TYPE_FSM__ns1__CommitFileResponse (22)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__CommitFileResponse(struct soap*, const char*, int, const _ns1__CommitFileResponse *, const char*);
SOAP_FMAC3 _ns1__CommitFileResponse * SOAP_FMAC4 soap_get__ns1__CommitFileResponse(struct soap*, _ns1__CommitFileResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__CommitFileResponse * SOAP_FMAC4 soap_in__ns1__CommitFileResponse(struct soap*, const char*, _ns1__CommitFileResponse *, const char*);

#define soap_new__ns1__CommitFileResponse(soap, n) soap_instantiate__ns1__CommitFileResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__CommitFileResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__CommitFileResponse * SOAP_FMAC4 soap_instantiate__ns1__CommitFileResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__CommitFileResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM__ns1__CommitFile
#define SOAP_TYPE_FSM__ns1__CommitFile (21)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__CommitFile(struct soap*, const char*, int, const _ns1__CommitFile *, const char*);
SOAP_FMAC3 _ns1__CommitFile * SOAP_FMAC4 soap_get__ns1__CommitFile(struct soap*, _ns1__CommitFile *, const char*, const char*);
SOAP_FMAC3 _ns1__CommitFile * SOAP_FMAC4 soap_in__ns1__CommitFile(struct soap*, const char*, _ns1__CommitFile *, const char*);

#define soap_new__ns1__CommitFile(soap, n) soap_instantiate__ns1__CommitFile(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__CommitFile(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__CommitFile * SOAP_FMAC4 soap_instantiate__ns1__CommitFile(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__CommitFile(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM__ns1__ProgressNotifyResponse
#define SOAP_TYPE_FSM__ns1__ProgressNotifyResponse (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__ProgressNotifyResponse(struct soap*, const char*, int, const _ns1__ProgressNotifyResponse *, const char*);
SOAP_FMAC3 _ns1__ProgressNotifyResponse * SOAP_FMAC4 soap_get__ns1__ProgressNotifyResponse(struct soap*, _ns1__ProgressNotifyResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__ProgressNotifyResponse * SOAP_FMAC4 soap_in__ns1__ProgressNotifyResponse(struct soap*, const char*, _ns1__ProgressNotifyResponse *, const char*);

#define soap_new__ns1__ProgressNotifyResponse(soap, n) soap_instantiate__ns1__ProgressNotifyResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__ProgressNotifyResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__ProgressNotifyResponse * SOAP_FMAC4 soap_instantiate__ns1__ProgressNotifyResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__ProgressNotifyResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM__ns1__ProgressNotify
#define SOAP_TYPE_FSM__ns1__ProgressNotify (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__ProgressNotify(struct soap*, const char*, int, const _ns1__ProgressNotify *, const char*);
SOAP_FMAC3 _ns1__ProgressNotify * SOAP_FMAC4 soap_get__ns1__ProgressNotify(struct soap*, _ns1__ProgressNotify *, const char*, const char*);
SOAP_FMAC3 _ns1__ProgressNotify * SOAP_FMAC4 soap_in__ns1__ProgressNotify(struct soap*, const char*, _ns1__ProgressNotify *, const char*);

#define soap_new__ns1__ProgressNotify(soap, n) soap_instantiate__ns1__ProgressNotify(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__ProgressNotify(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__ProgressNotify * SOAP_FMAC4 soap_instantiate__ns1__ProgressNotify(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__ProgressNotify(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM__ns1__CommitFileSetResponse
#define SOAP_TYPE_FSM__ns1__CommitFileSetResponse (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__CommitFileSetResponse(struct soap*, const char*, int, const _ns1__CommitFileSetResponse *, const char*);
SOAP_FMAC3 _ns1__CommitFileSetResponse * SOAP_FMAC4 soap_get__ns1__CommitFileSetResponse(struct soap*, _ns1__CommitFileSetResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__CommitFileSetResponse * SOAP_FMAC4 soap_in__ns1__CommitFileSetResponse(struct soap*, const char*, _ns1__CommitFileSetResponse *, const char*);

#define soap_new__ns1__CommitFileSetResponse(soap, n) soap_instantiate__ns1__CommitFileSetResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__CommitFileSetResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__CommitFileSetResponse * SOAP_FMAC4 soap_instantiate__ns1__CommitFileSetResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__CommitFileSetResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM__ns1__CommitFileSet
#define SOAP_TYPE_FSM__ns1__CommitFileSet (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__CommitFileSet(struct soap*, const char*, int, const _ns1__CommitFileSet *, const char*);
SOAP_FMAC3 _ns1__CommitFileSet * SOAP_FMAC4 soap_get__ns1__CommitFileSet(struct soap*, _ns1__CommitFileSet *, const char*, const char*);
SOAP_FMAC3 _ns1__CommitFileSet * SOAP_FMAC4 soap_in__ns1__CommitFileSet(struct soap*, const char*, _ns1__CommitFileSet *, const char*);

#define soap_new__ns1__CommitFileSet(soap, n) soap_instantiate__ns1__CommitFileSet(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__CommitFileSet(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__CommitFileSet * SOAP_FMAC4 soap_instantiate__ns1__CommitFileSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__CommitFileSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM__ns1__DeleteFileSetResponse
#define SOAP_TYPE_FSM__ns1__DeleteFileSetResponse (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__DeleteFileSetResponse(struct soap*, const char*, int, const _ns1__DeleteFileSetResponse *, const char*);
SOAP_FMAC3 _ns1__DeleteFileSetResponse * SOAP_FMAC4 soap_get__ns1__DeleteFileSetResponse(struct soap*, _ns1__DeleteFileSetResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__DeleteFileSetResponse * SOAP_FMAC4 soap_in__ns1__DeleteFileSetResponse(struct soap*, const char*, _ns1__DeleteFileSetResponse *, const char*);

#define soap_new__ns1__DeleteFileSetResponse(soap, n) soap_instantiate__ns1__DeleteFileSetResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__DeleteFileSetResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__DeleteFileSetResponse * SOAP_FMAC4 soap_instantiate__ns1__DeleteFileSetResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__DeleteFileSetResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM__ns1__DeleteFileSet
#define SOAP_TYPE_FSM__ns1__DeleteFileSet (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__DeleteFileSet(struct soap*, const char*, int, const _ns1__DeleteFileSet *, const char*);
SOAP_FMAC3 _ns1__DeleteFileSet * SOAP_FMAC4 soap_get__ns1__DeleteFileSet(struct soap*, _ns1__DeleteFileSet *, const char*, const char*);
SOAP_FMAC3 _ns1__DeleteFileSet * SOAP_FMAC4 soap_in__ns1__DeleteFileSet(struct soap*, const char*, _ns1__DeleteFileSet *, const char*);

#define soap_new__ns1__DeleteFileSet(soap, n) soap_instantiate__ns1__DeleteFileSet(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__DeleteFileSet(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__DeleteFileSet * SOAP_FMAC4 soap_instantiate__ns1__DeleteFileSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__DeleteFileSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM__ns1__QureyFileSetResponse
#define SOAP_TYPE_FSM__ns1__QureyFileSetResponse (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__QureyFileSetResponse(struct soap*, const char*, int, const _ns1__QureyFileSetResponse *, const char*);
SOAP_FMAC3 _ns1__QureyFileSetResponse * SOAP_FMAC4 soap_get__ns1__QureyFileSetResponse(struct soap*, _ns1__QureyFileSetResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__QureyFileSetResponse * SOAP_FMAC4 soap_in__ns1__QureyFileSetResponse(struct soap*, const char*, _ns1__QureyFileSetResponse *, const char*);

#define soap_new__ns1__QureyFileSetResponse(soap, n) soap_instantiate__ns1__QureyFileSetResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__QureyFileSetResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__QureyFileSetResponse * SOAP_FMAC4 soap_instantiate__ns1__QureyFileSetResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__QureyFileSetResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM__ns1__QureyFileSet
#define SOAP_TYPE_FSM__ns1__QureyFileSet (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__QureyFileSet(struct soap*, const char*, int, const _ns1__QureyFileSet *, const char*);
SOAP_FMAC3 _ns1__QureyFileSet * SOAP_FMAC4 soap_get__ns1__QureyFileSet(struct soap*, _ns1__QureyFileSet *, const char*, const char*);
SOAP_FMAC3 _ns1__QureyFileSet * SOAP_FMAC4 soap_in__ns1__QureyFileSet(struct soap*, const char*, _ns1__QureyFileSet *, const char*);

#define soap_new__ns1__QureyFileSet(soap, n) soap_instantiate__ns1__QureyFileSet(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__QureyFileSet(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__QureyFileSet * SOAP_FMAC4 soap_instantiate__ns1__QureyFileSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__QureyFileSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM__ns1__CreateFileSetResponse
#define SOAP_TYPE_FSM__ns1__CreateFileSetResponse (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__CreateFileSetResponse(struct soap*, const char*, int, const _ns1__CreateFileSetResponse *, const char*);
SOAP_FMAC3 _ns1__CreateFileSetResponse * SOAP_FMAC4 soap_get__ns1__CreateFileSetResponse(struct soap*, _ns1__CreateFileSetResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__CreateFileSetResponse * SOAP_FMAC4 soap_in__ns1__CreateFileSetResponse(struct soap*, const char*, _ns1__CreateFileSetResponse *, const char*);

#define soap_new__ns1__CreateFileSetResponse(soap, n) soap_instantiate__ns1__CreateFileSetResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__CreateFileSetResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__CreateFileSetResponse * SOAP_FMAC4 soap_instantiate__ns1__CreateFileSetResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__CreateFileSetResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM__ns1__CreateFileSet
#define SOAP_TYPE_FSM__ns1__CreateFileSet (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__CreateFileSet(struct soap*, const char*, int, const _ns1__CreateFileSet *, const char*);
SOAP_FMAC3 _ns1__CreateFileSet * SOAP_FMAC4 soap_get__ns1__CreateFileSet(struct soap*, _ns1__CreateFileSet *, const char*, const char*);
SOAP_FMAC3 _ns1__CreateFileSet * SOAP_FMAC4 soap_in__ns1__CreateFileSet(struct soap*, const char*, _ns1__CreateFileSet *, const char*);

#define soap_new__ns1__CreateFileSet(soap, n) soap_instantiate__ns1__CreateFileSet(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__CreateFileSet(soap, p) soap_delete(soap, p)

SOAP_FMAC3 _ns1__CreateFileSet * SOAP_FMAC4 soap_instantiate__ns1__CreateFileSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__CreateFileSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM_ns1__File
#define SOAP_TYPE_FSM_ns1__File (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__File(struct soap*, const char*, int, const ns1__File *, const char*);
SOAP_FMAC3 ns1__File * SOAP_FMAC4 soap_get_ns1__File(struct soap*, ns1__File *, const char*, const char*);
SOAP_FMAC3 ns1__File * SOAP_FMAC4 soap_in_ns1__File(struct soap*, const char*, ns1__File *, const char*);

#define soap_new_ns1__File(soap, n) soap_instantiate_ns1__File(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__File(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns1__File * SOAP_FMAC4 soap_instantiate_ns1__File(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__File(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM_ns1__ArrayOfFile
#define SOAP_TYPE_FSM_ns1__ArrayOfFile (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ArrayOfFile(struct soap*, const char*, int, const ns1__ArrayOfFile *, const char*);
SOAP_FMAC3 ns1__ArrayOfFile * SOAP_FMAC4 soap_get_ns1__ArrayOfFile(struct soap*, ns1__ArrayOfFile *, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfFile * SOAP_FMAC4 soap_in_ns1__ArrayOfFile(struct soap*, const char*, ns1__ArrayOfFile *, const char*);

#define soap_new_ns1__ArrayOfFile(soap, n) soap_instantiate_ns1__ArrayOfFile(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__ArrayOfFile(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns1__ArrayOfFile * SOAP_FMAC4 soap_instantiate_ns1__ArrayOfFile(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__ArrayOfFile(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM_ns1__FileSet
#define SOAP_TYPE_FSM_ns1__FileSet (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__FileSet(struct soap*, const char*, int, const ns1__FileSet *, const char*);
SOAP_FMAC3 ns1__FileSet * SOAP_FMAC4 soap_get_ns1__FileSet(struct soap*, ns1__FileSet *, const char*, const char*);
SOAP_FMAC3 ns1__FileSet * SOAP_FMAC4 soap_in_ns1__FileSet(struct soap*, const char*, ns1__FileSet *, const char*);

#define soap_new_ns1__FileSet(soap, n) soap_instantiate_ns1__FileSet(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__FileSet(soap, p) soap_delete(soap, p)

SOAP_FMAC3 ns1__FileSet * SOAP_FMAC4 soap_instantiate_ns1__FileSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__FileSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_FSM_SOAP_ENV__Fault
#define SOAP_TYPE_FSM_SOAP_ENV__Fault (83)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_FSM_SOAP_ENV__Reason
#define SOAP_TYPE_FSM_SOAP_ENV__Reason (82)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_FSM_SOAP_ENV__Detail
#define SOAP_TYPE_FSM_SOAP_ENV__Detail (79)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_FSM_SOAP_ENV__Code
#define SOAP_TYPE_FSM_SOAP_ENV__Code (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_FSM_SOAP_ENV__Header
#define SOAP_TYPE_FSM_SOAP_ENV__Header (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_FSM___ns3__CommitError
#define SOAP_TYPE_FSM___ns3__CommitError (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__CommitError(struct soap*, struct __ns3__CommitError *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__CommitError(struct soap*, const struct __ns3__CommitError *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__CommitError(struct soap*, const struct __ns3__CommitError *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__CommitError(struct soap*, const char*, int, const struct __ns3__CommitError *, const char*);
SOAP_FMAC3 struct __ns3__CommitError * SOAP_FMAC4 soap_get___ns3__CommitError(struct soap*, struct __ns3__CommitError *, const char*, const char*);
SOAP_FMAC3 struct __ns3__CommitError * SOAP_FMAC4 soap_in___ns3__CommitError(struct soap*, const char*, struct __ns3__CommitError *, const char*);

#define soap_new___ns3__CommitError(soap, n) soap_instantiate___ns3__CommitError(soap, n, NULL, NULL, NULL)


#define soap_delete___ns3__CommitError(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns3__CommitError * SOAP_FMAC4 soap_instantiate___ns3__CommitError(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__CommitError(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM___ns3__CommitFile
#define SOAP_TYPE_FSM___ns3__CommitFile (73)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__CommitFile(struct soap*, struct __ns3__CommitFile *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__CommitFile(struct soap*, const struct __ns3__CommitFile *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__CommitFile(struct soap*, const struct __ns3__CommitFile *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__CommitFile(struct soap*, const char*, int, const struct __ns3__CommitFile *, const char*);
SOAP_FMAC3 struct __ns3__CommitFile * SOAP_FMAC4 soap_get___ns3__CommitFile(struct soap*, struct __ns3__CommitFile *, const char*, const char*);
SOAP_FMAC3 struct __ns3__CommitFile * SOAP_FMAC4 soap_in___ns3__CommitFile(struct soap*, const char*, struct __ns3__CommitFile *, const char*);

#define soap_new___ns3__CommitFile(soap, n) soap_instantiate___ns3__CommitFile(soap, n, NULL, NULL, NULL)


#define soap_delete___ns3__CommitFile(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns3__CommitFile * SOAP_FMAC4 soap_instantiate___ns3__CommitFile(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__CommitFile(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM___ns3__ProgressNotify
#define SOAP_TYPE_FSM___ns3__ProgressNotify (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__ProgressNotify(struct soap*, struct __ns3__ProgressNotify *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__ProgressNotify(struct soap*, const struct __ns3__ProgressNotify *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__ProgressNotify(struct soap*, const struct __ns3__ProgressNotify *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__ProgressNotify(struct soap*, const char*, int, const struct __ns3__ProgressNotify *, const char*);
SOAP_FMAC3 struct __ns3__ProgressNotify * SOAP_FMAC4 soap_get___ns3__ProgressNotify(struct soap*, struct __ns3__ProgressNotify *, const char*, const char*);
SOAP_FMAC3 struct __ns3__ProgressNotify * SOAP_FMAC4 soap_in___ns3__ProgressNotify(struct soap*, const char*, struct __ns3__ProgressNotify *, const char*);

#define soap_new___ns3__ProgressNotify(soap, n) soap_instantiate___ns3__ProgressNotify(soap, n, NULL, NULL, NULL)


#define soap_delete___ns3__ProgressNotify(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns3__ProgressNotify * SOAP_FMAC4 soap_instantiate___ns3__ProgressNotify(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__ProgressNotify(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM___ns3__CommitFileSet
#define SOAP_TYPE_FSM___ns3__CommitFileSet (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__CommitFileSet(struct soap*, struct __ns3__CommitFileSet *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__CommitFileSet(struct soap*, const struct __ns3__CommitFileSet *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__CommitFileSet(struct soap*, const struct __ns3__CommitFileSet *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__CommitFileSet(struct soap*, const char*, int, const struct __ns3__CommitFileSet *, const char*);
SOAP_FMAC3 struct __ns3__CommitFileSet * SOAP_FMAC4 soap_get___ns3__CommitFileSet(struct soap*, struct __ns3__CommitFileSet *, const char*, const char*);
SOAP_FMAC3 struct __ns3__CommitFileSet * SOAP_FMAC4 soap_in___ns3__CommitFileSet(struct soap*, const char*, struct __ns3__CommitFileSet *, const char*);

#define soap_new___ns3__CommitFileSet(soap, n) soap_instantiate___ns3__CommitFileSet(soap, n, NULL, NULL, NULL)


#define soap_delete___ns3__CommitFileSet(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns3__CommitFileSet * SOAP_FMAC4 soap_instantiate___ns3__CommitFileSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__CommitFileSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM___ns3__DeleteFileSet
#define SOAP_TYPE_FSM___ns3__DeleteFileSet (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__DeleteFileSet(struct soap*, struct __ns3__DeleteFileSet *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__DeleteFileSet(struct soap*, const struct __ns3__DeleteFileSet *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__DeleteFileSet(struct soap*, const struct __ns3__DeleteFileSet *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__DeleteFileSet(struct soap*, const char*, int, const struct __ns3__DeleteFileSet *, const char*);
SOAP_FMAC3 struct __ns3__DeleteFileSet * SOAP_FMAC4 soap_get___ns3__DeleteFileSet(struct soap*, struct __ns3__DeleteFileSet *, const char*, const char*);
SOAP_FMAC3 struct __ns3__DeleteFileSet * SOAP_FMAC4 soap_in___ns3__DeleteFileSet(struct soap*, const char*, struct __ns3__DeleteFileSet *, const char*);

#define soap_new___ns3__DeleteFileSet(soap, n) soap_instantiate___ns3__DeleteFileSet(soap, n, NULL, NULL, NULL)


#define soap_delete___ns3__DeleteFileSet(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns3__DeleteFileSet * SOAP_FMAC4 soap_instantiate___ns3__DeleteFileSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__DeleteFileSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM___ns3__QureyFileSet
#define SOAP_TYPE_FSM___ns3__QureyFileSet (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__QureyFileSet(struct soap*, struct __ns3__QureyFileSet *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__QureyFileSet(struct soap*, const struct __ns3__QureyFileSet *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__QureyFileSet(struct soap*, const struct __ns3__QureyFileSet *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__QureyFileSet(struct soap*, const char*, int, const struct __ns3__QureyFileSet *, const char*);
SOAP_FMAC3 struct __ns3__QureyFileSet * SOAP_FMAC4 soap_get___ns3__QureyFileSet(struct soap*, struct __ns3__QureyFileSet *, const char*, const char*);
SOAP_FMAC3 struct __ns3__QureyFileSet * SOAP_FMAC4 soap_in___ns3__QureyFileSet(struct soap*, const char*, struct __ns3__QureyFileSet *, const char*);

#define soap_new___ns3__QureyFileSet(soap, n) soap_instantiate___ns3__QureyFileSet(soap, n, NULL, NULL, NULL)


#define soap_delete___ns3__QureyFileSet(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns3__QureyFileSet * SOAP_FMAC4 soap_instantiate___ns3__QureyFileSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__QureyFileSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM___ns3__CreateFileSet
#define SOAP_TYPE_FSM___ns3__CreateFileSet (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns3__CreateFileSet(struct soap*, struct __ns3__CreateFileSet *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns3__CreateFileSet(struct soap*, const struct __ns3__CreateFileSet *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns3__CreateFileSet(struct soap*, const struct __ns3__CreateFileSet *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns3__CreateFileSet(struct soap*, const char*, int, const struct __ns3__CreateFileSet *, const char*);
SOAP_FMAC3 struct __ns3__CreateFileSet * SOAP_FMAC4 soap_get___ns3__CreateFileSet(struct soap*, struct __ns3__CreateFileSet *, const char*, const char*);
SOAP_FMAC3 struct __ns3__CreateFileSet * SOAP_FMAC4 soap_in___ns3__CreateFileSet(struct soap*, const char*, struct __ns3__CreateFileSet *, const char*);

#define soap_new___ns3__CreateFileSet(soap, n) soap_instantiate___ns3__CreateFileSet(soap, n, NULL, NULL, NULL)


#define soap_delete___ns3__CreateFileSet(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns3__CreateFileSet * SOAP_FMAC4 soap_instantiate___ns3__CreateFileSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns3__CreateFileSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM___ns2__CommitError
#define SOAP_TYPE_FSM___ns2__CommitError (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__CommitError(struct soap*, struct __ns2__CommitError *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__CommitError(struct soap*, const struct __ns2__CommitError *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__CommitError(struct soap*, const struct __ns2__CommitError *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__CommitError(struct soap*, const char*, int, const struct __ns2__CommitError *, const char*);
SOAP_FMAC3 struct __ns2__CommitError * SOAP_FMAC4 soap_get___ns2__CommitError(struct soap*, struct __ns2__CommitError *, const char*, const char*);
SOAP_FMAC3 struct __ns2__CommitError * SOAP_FMAC4 soap_in___ns2__CommitError(struct soap*, const char*, struct __ns2__CommitError *, const char*);

#define soap_new___ns2__CommitError(soap, n) soap_instantiate___ns2__CommitError(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__CommitError(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns2__CommitError * SOAP_FMAC4 soap_instantiate___ns2__CommitError(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__CommitError(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM___ns2__CommitFile
#define SOAP_TYPE_FSM___ns2__CommitFile (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__CommitFile(struct soap*, struct __ns2__CommitFile *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__CommitFile(struct soap*, const struct __ns2__CommitFile *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__CommitFile(struct soap*, const struct __ns2__CommitFile *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__CommitFile(struct soap*, const char*, int, const struct __ns2__CommitFile *, const char*);
SOAP_FMAC3 struct __ns2__CommitFile * SOAP_FMAC4 soap_get___ns2__CommitFile(struct soap*, struct __ns2__CommitFile *, const char*, const char*);
SOAP_FMAC3 struct __ns2__CommitFile * SOAP_FMAC4 soap_in___ns2__CommitFile(struct soap*, const char*, struct __ns2__CommitFile *, const char*);

#define soap_new___ns2__CommitFile(soap, n) soap_instantiate___ns2__CommitFile(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__CommitFile(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns2__CommitFile * SOAP_FMAC4 soap_instantiate___ns2__CommitFile(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__CommitFile(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM___ns2__ProgressNotify
#define SOAP_TYPE_FSM___ns2__ProgressNotify (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__ProgressNotify(struct soap*, struct __ns2__ProgressNotify *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__ProgressNotify(struct soap*, const struct __ns2__ProgressNotify *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__ProgressNotify(struct soap*, const struct __ns2__ProgressNotify *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__ProgressNotify(struct soap*, const char*, int, const struct __ns2__ProgressNotify *, const char*);
SOAP_FMAC3 struct __ns2__ProgressNotify * SOAP_FMAC4 soap_get___ns2__ProgressNotify(struct soap*, struct __ns2__ProgressNotify *, const char*, const char*);
SOAP_FMAC3 struct __ns2__ProgressNotify * SOAP_FMAC4 soap_in___ns2__ProgressNotify(struct soap*, const char*, struct __ns2__ProgressNotify *, const char*);

#define soap_new___ns2__ProgressNotify(soap, n) soap_instantiate___ns2__ProgressNotify(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__ProgressNotify(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns2__ProgressNotify * SOAP_FMAC4 soap_instantiate___ns2__ProgressNotify(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__ProgressNotify(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM___ns2__CommitFileSet
#define SOAP_TYPE_FSM___ns2__CommitFileSet (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__CommitFileSet(struct soap*, struct __ns2__CommitFileSet *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__CommitFileSet(struct soap*, const struct __ns2__CommitFileSet *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__CommitFileSet(struct soap*, const struct __ns2__CommitFileSet *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__CommitFileSet(struct soap*, const char*, int, const struct __ns2__CommitFileSet *, const char*);
SOAP_FMAC3 struct __ns2__CommitFileSet * SOAP_FMAC4 soap_get___ns2__CommitFileSet(struct soap*, struct __ns2__CommitFileSet *, const char*, const char*);
SOAP_FMAC3 struct __ns2__CommitFileSet * SOAP_FMAC4 soap_in___ns2__CommitFileSet(struct soap*, const char*, struct __ns2__CommitFileSet *, const char*);

#define soap_new___ns2__CommitFileSet(soap, n) soap_instantiate___ns2__CommitFileSet(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__CommitFileSet(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns2__CommitFileSet * SOAP_FMAC4 soap_instantiate___ns2__CommitFileSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__CommitFileSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM___ns2__DeleteFileSet
#define SOAP_TYPE_FSM___ns2__DeleteFileSet (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__DeleteFileSet(struct soap*, struct __ns2__DeleteFileSet *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__DeleteFileSet(struct soap*, const struct __ns2__DeleteFileSet *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__DeleteFileSet(struct soap*, const struct __ns2__DeleteFileSet *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__DeleteFileSet(struct soap*, const char*, int, const struct __ns2__DeleteFileSet *, const char*);
SOAP_FMAC3 struct __ns2__DeleteFileSet * SOAP_FMAC4 soap_get___ns2__DeleteFileSet(struct soap*, struct __ns2__DeleteFileSet *, const char*, const char*);
SOAP_FMAC3 struct __ns2__DeleteFileSet * SOAP_FMAC4 soap_in___ns2__DeleteFileSet(struct soap*, const char*, struct __ns2__DeleteFileSet *, const char*);

#define soap_new___ns2__DeleteFileSet(soap, n) soap_instantiate___ns2__DeleteFileSet(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__DeleteFileSet(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns2__DeleteFileSet * SOAP_FMAC4 soap_instantiate___ns2__DeleteFileSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__DeleteFileSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM___ns2__QureyFileSet
#define SOAP_TYPE_FSM___ns2__QureyFileSet (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__QureyFileSet(struct soap*, struct __ns2__QureyFileSet *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__QureyFileSet(struct soap*, const struct __ns2__QureyFileSet *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__QureyFileSet(struct soap*, const struct __ns2__QureyFileSet *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__QureyFileSet(struct soap*, const char*, int, const struct __ns2__QureyFileSet *, const char*);
SOAP_FMAC3 struct __ns2__QureyFileSet * SOAP_FMAC4 soap_get___ns2__QureyFileSet(struct soap*, struct __ns2__QureyFileSet *, const char*, const char*);
SOAP_FMAC3 struct __ns2__QureyFileSet * SOAP_FMAC4 soap_in___ns2__QureyFileSet(struct soap*, const char*, struct __ns2__QureyFileSet *, const char*);

#define soap_new___ns2__QureyFileSet(soap, n) soap_instantiate___ns2__QureyFileSet(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__QureyFileSet(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns2__QureyFileSet * SOAP_FMAC4 soap_instantiate___ns2__QureyFileSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__QureyFileSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_FSM___ns2__CreateFileSet
#define SOAP_TYPE_FSM___ns2__CreateFileSet (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns2__CreateFileSet(struct soap*, struct __ns2__CreateFileSet *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns2__CreateFileSet(struct soap*, const struct __ns2__CreateFileSet *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns2__CreateFileSet(struct soap*, const struct __ns2__CreateFileSet *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns2__CreateFileSet(struct soap*, const char*, int, const struct __ns2__CreateFileSet *, const char*);
SOAP_FMAC3 struct __ns2__CreateFileSet * SOAP_FMAC4 soap_get___ns2__CreateFileSet(struct soap*, struct __ns2__CreateFileSet *, const char*, const char*);
SOAP_FMAC3 struct __ns2__CreateFileSet * SOAP_FMAC4 soap_in___ns2__CreateFileSet(struct soap*, const char*, struct __ns2__CreateFileSet *, const char*);

#define soap_new___ns2__CreateFileSet(soap, n) soap_instantiate___ns2__CreateFileSet(soap, n, NULL, NULL, NULL)


#define soap_delete___ns2__CreateFileSet(soap, p) soap_delete(soap, p)

SOAP_FMAC3 struct __ns2__CreateFileSet * SOAP_FMAC4 soap_instantiate___ns2__CreateFileSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns2__CreateFileSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_FSM_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_FSM_PointerToSOAP_ENV__Reason (85)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_FSM_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_FSM_PointerToSOAP_ENV__Detail (84)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_FSM_PointerToSOAP_ENV__Code
#define SOAP_TYPE_FSM_PointerToSOAP_ENV__Code (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_FSM_PointerTo_ns1__CommitErrorResponse
#define SOAP_TYPE_FSM_PointerTo_ns1__CommitErrorResponse (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__CommitErrorResponse(struct soap*, _ns1__CommitErrorResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__CommitErrorResponse(struct soap*, _ns1__CommitErrorResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__CommitErrorResponse(struct soap*, const char *, int, _ns1__CommitErrorResponse *const*, const char *);
SOAP_FMAC3 _ns1__CommitErrorResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__CommitErrorResponse(struct soap*, _ns1__CommitErrorResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__CommitErrorResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__CommitErrorResponse(struct soap*, const char*, _ns1__CommitErrorResponse **, const char*);

#ifndef SOAP_TYPE_FSM_PointerTo_ns1__CommitError
#define SOAP_TYPE_FSM_PointerTo_ns1__CommitError (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__CommitError(struct soap*, _ns1__CommitError *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__CommitError(struct soap*, _ns1__CommitError *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__CommitError(struct soap*, const char *, int, _ns1__CommitError *const*, const char *);
SOAP_FMAC3 _ns1__CommitError ** SOAP_FMAC4 soap_get_PointerTo_ns1__CommitError(struct soap*, _ns1__CommitError **, const char*, const char*);
SOAP_FMAC3 _ns1__CommitError ** SOAP_FMAC4 soap_in_PointerTo_ns1__CommitError(struct soap*, const char*, _ns1__CommitError **, const char*);

#ifndef SOAP_TYPE_FSM_PointerTo_ns1__CommitFileResponse
#define SOAP_TYPE_FSM_PointerTo_ns1__CommitFileResponse (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__CommitFileResponse(struct soap*, _ns1__CommitFileResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__CommitFileResponse(struct soap*, _ns1__CommitFileResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__CommitFileResponse(struct soap*, const char *, int, _ns1__CommitFileResponse *const*, const char *);
SOAP_FMAC3 _ns1__CommitFileResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__CommitFileResponse(struct soap*, _ns1__CommitFileResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__CommitFileResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__CommitFileResponse(struct soap*, const char*, _ns1__CommitFileResponse **, const char*);

#ifndef SOAP_TYPE_FSM_PointerTo_ns1__CommitFile
#define SOAP_TYPE_FSM_PointerTo_ns1__CommitFile (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__CommitFile(struct soap*, _ns1__CommitFile *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__CommitFile(struct soap*, _ns1__CommitFile *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__CommitFile(struct soap*, const char *, int, _ns1__CommitFile *const*, const char *);
SOAP_FMAC3 _ns1__CommitFile ** SOAP_FMAC4 soap_get_PointerTo_ns1__CommitFile(struct soap*, _ns1__CommitFile **, const char*, const char*);
SOAP_FMAC3 _ns1__CommitFile ** SOAP_FMAC4 soap_in_PointerTo_ns1__CommitFile(struct soap*, const char*, _ns1__CommitFile **, const char*);

#ifndef SOAP_TYPE_FSM_PointerTo_ns1__ProgressNotifyResponse
#define SOAP_TYPE_FSM_PointerTo_ns1__ProgressNotifyResponse (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__ProgressNotifyResponse(struct soap*, _ns1__ProgressNotifyResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__ProgressNotifyResponse(struct soap*, _ns1__ProgressNotifyResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__ProgressNotifyResponse(struct soap*, const char *, int, _ns1__ProgressNotifyResponse *const*, const char *);
SOAP_FMAC3 _ns1__ProgressNotifyResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__ProgressNotifyResponse(struct soap*, _ns1__ProgressNotifyResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__ProgressNotifyResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__ProgressNotifyResponse(struct soap*, const char*, _ns1__ProgressNotifyResponse **, const char*);

#ifndef SOAP_TYPE_FSM_PointerTo_ns1__ProgressNotify
#define SOAP_TYPE_FSM_PointerTo_ns1__ProgressNotify (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__ProgressNotify(struct soap*, _ns1__ProgressNotify *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__ProgressNotify(struct soap*, _ns1__ProgressNotify *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__ProgressNotify(struct soap*, const char *, int, _ns1__ProgressNotify *const*, const char *);
SOAP_FMAC3 _ns1__ProgressNotify ** SOAP_FMAC4 soap_get_PointerTo_ns1__ProgressNotify(struct soap*, _ns1__ProgressNotify **, const char*, const char*);
SOAP_FMAC3 _ns1__ProgressNotify ** SOAP_FMAC4 soap_in_PointerTo_ns1__ProgressNotify(struct soap*, const char*, _ns1__ProgressNotify **, const char*);

#ifndef SOAP_TYPE_FSM_PointerTo_ns1__CommitFileSetResponse
#define SOAP_TYPE_FSM_PointerTo_ns1__CommitFileSetResponse (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__CommitFileSetResponse(struct soap*, _ns1__CommitFileSetResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__CommitFileSetResponse(struct soap*, _ns1__CommitFileSetResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__CommitFileSetResponse(struct soap*, const char *, int, _ns1__CommitFileSetResponse *const*, const char *);
SOAP_FMAC3 _ns1__CommitFileSetResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__CommitFileSetResponse(struct soap*, _ns1__CommitFileSetResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__CommitFileSetResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__CommitFileSetResponse(struct soap*, const char*, _ns1__CommitFileSetResponse **, const char*);

#ifndef SOAP_TYPE_FSM_PointerTo_ns1__CommitFileSet
#define SOAP_TYPE_FSM_PointerTo_ns1__CommitFileSet (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__CommitFileSet(struct soap*, _ns1__CommitFileSet *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__CommitFileSet(struct soap*, _ns1__CommitFileSet *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__CommitFileSet(struct soap*, const char *, int, _ns1__CommitFileSet *const*, const char *);
SOAP_FMAC3 _ns1__CommitFileSet ** SOAP_FMAC4 soap_get_PointerTo_ns1__CommitFileSet(struct soap*, _ns1__CommitFileSet **, const char*, const char*);
SOAP_FMAC3 _ns1__CommitFileSet ** SOAP_FMAC4 soap_in_PointerTo_ns1__CommitFileSet(struct soap*, const char*, _ns1__CommitFileSet **, const char*);

#ifndef SOAP_TYPE_FSM_PointerTo_ns1__DeleteFileSetResponse
#define SOAP_TYPE_FSM_PointerTo_ns1__DeleteFileSetResponse (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__DeleteFileSetResponse(struct soap*, _ns1__DeleteFileSetResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__DeleteFileSetResponse(struct soap*, _ns1__DeleteFileSetResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__DeleteFileSetResponse(struct soap*, const char *, int, _ns1__DeleteFileSetResponse *const*, const char *);
SOAP_FMAC3 _ns1__DeleteFileSetResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__DeleteFileSetResponse(struct soap*, _ns1__DeleteFileSetResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__DeleteFileSetResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__DeleteFileSetResponse(struct soap*, const char*, _ns1__DeleteFileSetResponse **, const char*);

#ifndef SOAP_TYPE_FSM_PointerTo_ns1__DeleteFileSet
#define SOAP_TYPE_FSM_PointerTo_ns1__DeleteFileSet (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__DeleteFileSet(struct soap*, _ns1__DeleteFileSet *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__DeleteFileSet(struct soap*, _ns1__DeleteFileSet *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__DeleteFileSet(struct soap*, const char *, int, _ns1__DeleteFileSet *const*, const char *);
SOAP_FMAC3 _ns1__DeleteFileSet ** SOAP_FMAC4 soap_get_PointerTo_ns1__DeleteFileSet(struct soap*, _ns1__DeleteFileSet **, const char*, const char*);
SOAP_FMAC3 _ns1__DeleteFileSet ** SOAP_FMAC4 soap_in_PointerTo_ns1__DeleteFileSet(struct soap*, const char*, _ns1__DeleteFileSet **, const char*);

#ifndef SOAP_TYPE_FSM_PointerTo_ns1__QureyFileSetResponse
#define SOAP_TYPE_FSM_PointerTo_ns1__QureyFileSetResponse (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__QureyFileSetResponse(struct soap*, _ns1__QureyFileSetResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__QureyFileSetResponse(struct soap*, _ns1__QureyFileSetResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__QureyFileSetResponse(struct soap*, const char *, int, _ns1__QureyFileSetResponse *const*, const char *);
SOAP_FMAC3 _ns1__QureyFileSetResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__QureyFileSetResponse(struct soap*, _ns1__QureyFileSetResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__QureyFileSetResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__QureyFileSetResponse(struct soap*, const char*, _ns1__QureyFileSetResponse **, const char*);

#ifndef SOAP_TYPE_FSM_PointerTo_ns1__QureyFileSet
#define SOAP_TYPE_FSM_PointerTo_ns1__QureyFileSet (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__QureyFileSet(struct soap*, _ns1__QureyFileSet *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__QureyFileSet(struct soap*, _ns1__QureyFileSet *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__QureyFileSet(struct soap*, const char *, int, _ns1__QureyFileSet *const*, const char *);
SOAP_FMAC3 _ns1__QureyFileSet ** SOAP_FMAC4 soap_get_PointerTo_ns1__QureyFileSet(struct soap*, _ns1__QureyFileSet **, const char*, const char*);
SOAP_FMAC3 _ns1__QureyFileSet ** SOAP_FMAC4 soap_in_PointerTo_ns1__QureyFileSet(struct soap*, const char*, _ns1__QureyFileSet **, const char*);

#ifndef SOAP_TYPE_FSM_PointerTo_ns1__CreateFileSetResponse
#define SOAP_TYPE_FSM_PointerTo_ns1__CreateFileSetResponse (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__CreateFileSetResponse(struct soap*, _ns1__CreateFileSetResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__CreateFileSetResponse(struct soap*, _ns1__CreateFileSetResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__CreateFileSetResponse(struct soap*, const char *, int, _ns1__CreateFileSetResponse *const*, const char *);
SOAP_FMAC3 _ns1__CreateFileSetResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__CreateFileSetResponse(struct soap*, _ns1__CreateFileSetResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__CreateFileSetResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__CreateFileSetResponse(struct soap*, const char*, _ns1__CreateFileSetResponse **, const char*);

#ifndef SOAP_TYPE_FSM_PointerTo_ns1__CreateFileSet
#define SOAP_TYPE_FSM_PointerTo_ns1__CreateFileSet (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__CreateFileSet(struct soap*, _ns1__CreateFileSet *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__CreateFileSet(struct soap*, _ns1__CreateFileSet *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__CreateFileSet(struct soap*, const char *, int, _ns1__CreateFileSet *const*, const char *);
SOAP_FMAC3 _ns1__CreateFileSet ** SOAP_FMAC4 soap_get_PointerTo_ns1__CreateFileSet(struct soap*, _ns1__CreateFileSet **, const char*, const char*);
SOAP_FMAC3 _ns1__CreateFileSet ** SOAP_FMAC4 soap_in_PointerTo_ns1__CreateFileSet(struct soap*, const char*, _ns1__CreateFileSet **, const char*);

#ifndef SOAP_TYPE_FSM_PointerTons1__FileSet
#define SOAP_TYPE_FSM_PointerTons1__FileSet (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__FileSet(struct soap*, ns1__FileSet *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__FileSet(struct soap*, ns1__FileSet *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__FileSet(struct soap*, const char *, int, ns1__FileSet *const*, const char *);
SOAP_FMAC3 ns1__FileSet ** SOAP_FMAC4 soap_get_PointerTons1__FileSet(struct soap*, ns1__FileSet **, const char*, const char*);
SOAP_FMAC3 ns1__FileSet ** SOAP_FMAC4 soap_in_PointerTons1__FileSet(struct soap*, const char*, ns1__FileSet **, const char*);

#ifndef SOAP_TYPE_FSM_PointerTons1__File
#define SOAP_TYPE_FSM_PointerTons1__File (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__File(struct soap*, ns1__File *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__File(struct soap*, ns1__File *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__File(struct soap*, const char *, int, ns1__File *const*, const char *);
SOAP_FMAC3 ns1__File ** SOAP_FMAC4 soap_get_PointerTons1__File(struct soap*, ns1__File **, const char*, const char*);
SOAP_FMAC3 ns1__File ** SOAP_FMAC4 soap_in_PointerTons1__File(struct soap*, const char*, ns1__File **, const char*);

#ifndef SOAP_TYPE_FSM_PointerTons1__ArrayOfFile
#define SOAP_TYPE_FSM_PointerTons1__ArrayOfFile (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ArrayOfFile(struct soap*, ns1__ArrayOfFile *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ArrayOfFile(struct soap*, ns1__ArrayOfFile *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ArrayOfFile(struct soap*, const char *, int, ns1__ArrayOfFile *const*, const char *);
SOAP_FMAC3 ns1__ArrayOfFile ** SOAP_FMAC4 soap_get_PointerTons1__ArrayOfFile(struct soap*, ns1__ArrayOfFile **, const char*, const char*);
SOAP_FMAC3 ns1__ArrayOfFile ** SOAP_FMAC4 soap_in_PointerTons1__ArrayOfFile(struct soap*, const char*, ns1__ArrayOfFile **, const char*);

#ifndef SOAP_TYPE_FSM_PointerTostd__string
#define SOAP_TYPE_FSM_PointerTostd__string (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);

#ifndef SOAP_TYPE_FSM__QName
#define SOAP_TYPE_FSM__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_FSM_string
#define SOAP_TYPE_FSM_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_FSM_std__vectorTemplateOfPointerTons1__File
#define SOAP_TYPE_FSM_std__vectorTemplateOfPointerTons1__File (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons1__File(struct soap*, std::vector<ns1__File * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons1__File(struct soap*, const std::vector<ns1__File * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons1__File(struct soap*, const char*, int, const std::vector<ns1__File * >*, const char*);
SOAP_FMAC3 std::vector<ns1__File * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons1__File(struct soap*, const char*, std::vector<ns1__File * >*, const char*);

#define soap_new_std__vectorTemplateOfPointerTons1__File(soap, n) soap_instantiate_std__vectorTemplateOfPointerTons1__File(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOfPointerTons1__File(soap, p) soap_delete(soap, p)

SOAP_FMAC3 std::vector<ns1__File * > * SOAP_FMAC4 soap_instantiate_std__vectorTemplateOfPointerTons1__File(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons1__File(struct soap*, int, int, void*, size_t, const void*, size_t);

} // namespace FSM


#endif

/* End of FSMH.h */
