/* FtpTransService.h
   Generated by gSOAP 2.7.14 from Control.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef FtpTransService_H
#define FtpTransService_H
#include "FtpH.h"
class SOAP_CMAC TransService : public soap
{ public:
	/// Constructor
	TransService();
	/// Constructor with copy of another engine state
	TransService(const struct soap&);
	/// Constructor with engine input+output mode control
	TransService(soap_mode iomode);
	/// Constructor with engine input and output mode control
	TransService(soap_mode imode, soap_mode omode);
	/// Destructor frees all data
	virtual ~TransService();
	/// Initializer used by constructor
	virtual	void TransService_init(soap_mode imode, soap_mode omode);
	/// Create a copy
	virtual	TransService *copy();
	/// Force close connection (normally automatic)
	virtual	int soap_close_socket();
	/// Return sender-related fault to sender
	virtual	int soap_senderfault(const char *string, const char *detailXML);
	/// Return sender-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Return receiver-related fault to sender
	virtual	int soap_receiverfault(const char *string, const char *detailXML);
	/// Return receiver-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Run simple single-thread iterative service on port until a connection error occurs (returns error code or SOAP_OK), use this->bind_flag = SO_REUSEADDR to rebind for a rerun
	virtual	int run(int port);
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog);
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept();
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve();
	/// Used by serve() to dispatch a request (returns error code or SOAP_OK)
	virtual	int dispatch();

	///
	/// Service operations (you should define these):
	///

	/// Web service operation 'Transform' (returns error code or SOAP_OK)
	virtual	int Transform(ftp__ArrayOfFile *flist, ftp__Position *position, int &response);

	/// Web service operation 'Stop' (returns error code or SOAP_OK)
	virtual	int Stop(int &response);

	/// Web service operation 'Start' (returns error code or SOAP_OK)
	virtual	int Start(int &response);

	/// Web service operation 'Pause' (returns error code or SOAP_OK)
	virtual	int Pause(int &response);

	/// Web service operation 'Resume' (returns error code or SOAP_OK)
	virtual	int Resume(int &response);

	/// Web service operation 'Delete' (returns error code or SOAP_OK)
	virtual	int Delete(LONG64 id, int &response);

	/// Web service operation 'DeleteAll' (returns error code or SOAP_OK)
	virtual	int DeleteAll(int &response);

	/// Web service operation 'GetState' (returns error code or SOAP_OK)
	virtual	int GetState(ftp__State *response);
};
#endif
